apiVersion: v1
kind: Service
metadata:
  name: mycelium-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app: mycelium-operator
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: api
  selector:
    app: mycelium-operator